### ISSUE TITLE
Require as an object property being replaced

### ISSUE THREAD

**Issue by guybedford** [systemjs/babel-plugin-transform-cjs-system-wrapper#8]
It looks like in the scenario:

```javascript
var x = {
  require: 'x'
}
```

That is being replaced with the require identifier to:

```javascript
var x = {
  $__require: 'x'
}
```

We should only be replacing `require` as an identifier expression within the scope rather.

**Comment by jrauschenbusch** [comment]
You mean we should only replace `require` at the top level scope of the factory function?

```javascript
SystemJS.registerDynamic('foobar', ['bar'], true, function ($__require, exports, module) {
  'use strict';

  // factory scope -> replace `require` with `$__require` within this scope

  var define,
      global = this || self,
      GLOBAL = global;

  var o1 = (function(require){
    // new scope, hence require identifiers should not replaced anymore if they are references to a local variable/param
    var foo = require('foo');
    return {
        require: '^foobar'
    };
  })($__require);

  var o2 = (function(){
     // new scope, but top level require is not hidden by a local variable/param. Hence replace `require` identifiers.
    var foo = $__require('foo');
    // object property keys should not be replaced, only assignments if necessary
    return {
        require: foo + $__require('bar')
    };
  })();

  return module.exports;
});
```

Or should we simple exclude the case that object property keys are replaced? The above logic would be more precise but we have to handle a lot of edge cases i think.

**Comment by guybedford** [comment]
Thanks for the update here. I've included this fix in https://github.com/systemjs/babel-plugin-transform-cjs-system-require/commit/bb6a6caf93bcc8e4c8f5cbbaf7fe501c933c77e6.

**Comment by jrauschenbusch** [comment]
@guybedford You're welcome! I've another idea which maybe could provide an abstraction of the more precise logic. I'll give it a try and give you some feedback.

**Comment by jrauschenbusch** [comment]
Hi @guybedford. I've done some investigation and here's the result in a separate branch: https://github.com/systemjs/babel-plugin-transform-cjs-system-wrapper/commit/0baec5ab45a84249ba9495dcd899ba2dbf7976da

It removes the dependency to the `cjs-system-require` plugin, since the replacement is performed directly inside the `cjs-system-wrapper` plugin.

I don't know if the cjs require detection is bypassed with this solution (i think this was the initial goal of the `require` rename thing). But it seems that only identifiers with a reference to the factory `require` will be renamed.

**Comment by jrauschenbusch** [comment]
Hint: As the test with `eval('typeof require') == 'undefined'` is not working anymore in this solution (nested scoped `require` identifiers will not replaced) i've fixed it with an `!=` expression.

**Comment by guybedford** [comment]
@jrauschenbusch thanks for looking into this... I forgot to update here though that with require replacement it is important to not actually do scope handling - this is what Browserify does and Webpack as well to my knowledge as we do need to support cases where the require statement is wrapped in a scoped function.
