### ISSUE TITLE
if `var module` is redeclared in outer scope, don't return module.exports

### ISSUE THREAD

**Issue by guybedford** [systemjs/babel-plugin-transform-cjs-system-wrapper#9]
This is a special case that needs handling, as described in https://github.com/systemjs/systemjs/issues/1490#issue-189207452.

**Comment by jrauschenbusch** [comment]
Hi @guybedford,

sorry for the late answer. I'm going to look into it and try to create a fix asap.

Is it really so easy to simply not return `module.exports` or do we need another solution?

**Comment by guybedford** [comment]
@jrauschenbusch thanks for getting back on this.

Thinking about this further, I'm wondering if we need to return `module.exports` at all? Perhaps it would be easier just to remove this entirely?

**Comment by jrauschenbusch** [comment]
Hi @guybedford,

I've created a bug fix for this problem. I also merged two other branches that were already prepared for integration. I will now open a PR so that you can perform a code review and do some Builder integration tests with real applications. (Packed plugin is in the repo)
